<?php

/** 
 * GentleSource Module AuctionAds - language.en.php
 * 
 * (C) Ralf Stadtaus http://www.gentlesource.com/
 * 
 * If you have translated this file into another
 * language, we would appreciate it if you would
 * send us the translated file. Thanks :-)
 * 
 */




$text = array(   

'txt_ad_campaign'                   => 'Campaign ID',
'txt_ad_campaign_description'       => 'The campaign ID is a string of letters and numbers. It is not the text that you entered when you created the campaign. It is automatically generated by AuctionAds when you create a new campaign. <br /><br />The campaign ID is not easy to obtain. In fact it is not shown in your Auction Ads account in plain text. There are two ways to find the campaign ID. Go to the campaign manager in your AuctionAds account. View the source text and look for the checkboxes. The value attribute contains the campaign ID. The other way would be – in Firefox – to view the page info. There is a tab named "Forms" that contains all form fields and values listed.',
'txt_ad_client'                     => 'Publisher ID',
'txt_ad_client_description'         => 'You can find your publisher ID in your AuctionAds account. It’s listed on "Account Home".',
'txt_ad_format'                     => 'Ad format', 
'txt_ad_format_banner'              => 'Banner',
'txt_ad_format_button'              => 'Button',
'txt_ad_format_half_banner'         => 'Half Banner',
'txt_ad_format_large_rectangle'     => 'Large Rectangle',
'txt_ad_format_medium_rectangle'    => 'Medium Rectangle',
'txt_ad_format_leaderboard'         => 'Leaderboard',
'txt_ad_format_small_rectangle'     => 'Small Rectangle',
'txt_ad_format_skyscraper'          => 'Skyscraper',
'txt_ad_format_square'              => 'Square',
'txt_ad_format_vertical_banner'     => 'Vertical Banner',
'txt_ad_format_wide_skyscraper'     => 'Wide Skyscraper',
'txt_ad_keywords'                   => 'Keywords',
'txt_ad_keywords_description'       => 'AuctionAds has published some helpful information about keywords. You should really check them out, but in short: Separate keywords by comma, separate keyword groups by semicolon, put a minus sign in front of keywords you want to exclude.', 

'txt_background_color'              => 'Background color',
'txt_border_color'                  => 'Outer border color',

'txt_enable_module'                 => 'Activate AuctionAds',
'txt_enable_module_description'     => '',

'txt_heading_color'                 => 'Heading Color',

'txt_link_color'                    => 'Link color',

'txt_module_description'            => 'Make money with your website and publish ads from AuctionAds. More information at <a href="http://www.auctionads.com/refer_9ed4505eaeb7d99a79d6" target="_blank">AuctionAds</a>.',
'txt_module_name'                   => 'AuctionAds',

'txt_new_window'                    => 'Open links in new window',

'txt_style'                         => 'Styles (CSS)',
'txt_style_description'             => 'If you are familiar with CSS, you can enter CSS code to format or position the ad block.',

'txt_text_color'                    => 'Text color',

);








?>
